-- 1. Criação da dim_praca
DROP TABLE IF EXISTS bridge_loja_praca;
DROP TABLE IF EXISTS dim_praca;

CREATE TABLE dim_praca (
    sk_praca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_praca VARCHAR(10),
    nome_praca VARCHAR(60),
    regional VARCHAR(30),
    domicilios_com_pet INT
);

-- 2. Linha -1 OBRIGATÓRIA na dimensão
INSERT INTO dim_praca (sk_praca, cod_praca, nome_praca, regional, domicilios_com_pet)
VALUES (-1, 'N/I', 'Nao Informado', 'Nao Informado', NULL);

-- 3. Carga da dim_praca
INSERT INTO dim_praca (cod_praca, nome_praca, regional, domicilios_com_pet)
SELECT DISTINCT
    "CodPraca",
    "NomePraca",
    "Regional",
    -- Retira o ponto de milhar antes de converter para inteiro
    CAST(REPLACE("DomiciliosComPet", '.', '') AS INT) AS domicilios_com_pet
FROM stg_loja_praca
WHERE "CodPraca" IS NOT NULL;


-- 4. Criação da bridge_loja_praca
CREATE TABLE bridge_loja_praca (
    cod_loja VARCHAR(10),
    sk_praca INT,
    fator_publico DECIMAL(6,4)
);

-- 5. Carga da bridge_loja_praca
INSERT INTO bridge_loja_praca (cod_loja, sk_praca, fator_publico)
SELECT 
    stg."CodLoja" AS cod_loja,
    dp.sk_praca,
    -- Troca vírgula por ponto para converter para decimal
    CAST(REPLACE(stg."PercentualPublico", ',', '.') AS DECIMAL(6,4)) AS fator_publico
FROM stg_loja_praca stg
-- Fazemos JOIN com a dimensão criada para buscar a chave artificial (sk_praca)
INNER JOIN dim_praca dp ON stg."CodPraca" = dp.cod_praca;

SELECT 'dim_praca' AS tabela, COUNT(*) AS total FROM dim_praca
UNION ALL
SELECT 'bridge_loja_praca' AS tabela, COUNT(*) AS total FROM bridge_loja_praca
UNION ALL
SELECT 'lojas_sem_fator_100%' AS tabela, COUNT(*) AS total 
FROM (
    SELECT cod_loja, SUM(fator_publico) AS soma_fator 
    FROM bridge_loja_praca 
    GROUP BY cod_loja 
    HAVING SUM(fator_publico) <> 1.00
) sub;