-- =====================================================================================
-- ARQUIVO 04: CRIAÇÃO E CARGA DA TABELA FATO_PEDIDO
-- =====================================================================================
TRUNCATE TABLE fato_pedido RESTART IDENTITY;
-- 1. RECRIANDO A ESTRUTURA OFICIAL DA TABELA FATO (Conforme Encarte 7)
DROP TABLE IF EXISTS fato_pedido;

CREATE TABLE fato_pedido (
    sk_pedido                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido             VARCHAR(20),
    sk_tempo_pedido           INT NOT NULL,
    sk_tempo_entrega          INT NOT NULL,
    sk_loja                   INT NOT NULL,
    sk_categoria              INT NOT NULL,
    houve_desconto            INT,
    canal_pedido              VARCHAR(20),
    dt_pedido                 TIMESTAMP,
    qt_itens                  INT,
    vl_liquido                DECIMAL(15,2),
    dias_integracao_separacao INT,
    dias_separacao_nota       INT,
    dias_nota_despacho        INT,
    dias_despacho_entrega     INT,
    dias_total_ate_entrega    INT
);

-- 2. CARGA DOS DADOS (O GRANDE CRUZAMENTO)
INSERT INTO fato_pedido (
    numero_pedido, sk_tempo_pedido, sk_tempo_entrega, sk_loja, sk_categoria,
    houve_desconto, canal_pedido, dt_pedido, qt_itens, vl_liquido,
    dias_integracao_separacao, dias_separacao_nota, dias_nota_despacho,
    dias_despacho_entrega, dias_total_ate_entrega
)
SELECT
    stg."NumeroPedido" AS numero_pedido,
    
    -- FK de Tempo (Pedido)
    CAST(TO_CHAR(TO_TIMESTAMP(stg."DtHoraPedido", 'MM/DD/YYYY HH12:MI AM'), 'YYYYMMDD') AS INT) AS sk_tempo_pedido,
    
    -- FK de Tempo (Entrega)
    COALESCE(CAST(TO_CHAR(NULLIF(TRIM(stg."DtEntregaCliente"), '')::date, 'YYYYMMDD') AS INT), -1) AS sk_tempo_entrega,
    
    -- FK de Loja
    COALESCE(l.sk_loja, -1) AS sk_loja,
    
    -- FK de Categoria
    COALESCE(c.sk_categoria, -1) AS sk_categoria,
    
    -- Padronização de Desconto
    CASE 
        WHEN UPPER(TRIM(stg."HouveDesconto")) IN ('S', 'SIM', '1', 'X', 'TRUE', 'V') THEN 1
        WHEN UPPER(TRIM(stg."HouveDesconto")) IN ('N', 'NAO', '0', 'FALSE', 'F') THEN 0
        ELSE NULL --"nao informado" é Nulo(vazio)
        --Ajuste para (Refatorado para Booleano/INT)        
    END AS houve_desconto,
    
    -- Padronização de Canal 
    CASE 
        WHEN UPPER(stg."CanalPedido") LIKE '%WHATS%' THEN 'WhatsApp'
        WHEN UPPER(stg."CanalPedido") LIKE '%APP%' THEN 'App'
        WHEN UPPER(stg."CanalPedido") LIKE '%SITE%' THEN 'Site'
        WHEN UPPER(stg."CanalPedido") LIKE '%LOJA%' THEN 'Loja Fisica'
        WHEN UPPER(stg."CanalPedido") LIKE '%TEL%' THEN 'Telefone'
        ELSE 'Nao Informado'
    END AS canal_pedido,
    
    -- Data do Pedido em Timestamp
    TO_TIMESTAMP(stg."DtHoraPedido", 'MM/DD/YYYY HH12:MI AM') AS dt_pedido,
    
    -- Métricas (AQUI ESTÁ A CORREÇÃO: Tratando os itens em branco)
    CASE 
        WHEN TRIM(stg."QTD.Itens") IN ('', '-') THEN NULL 
        ELSE CAST(stg."QTD.Itens" AS INT) 
    END AS qt_itens,
    
    -- A REGRA DOS NÚMEROS (Valor Líquido)
    CASE 
        WHEN TRIM(REPLACE(stg."ValorLiquidoPedido(R$)",'R$','')) IN ('','-') THEN NULL
        WHEN stg."ValorLiquidoPedido(R$)" LIKE '%,%' 
             THEN CAST(REPLACE(REPLACE(REPLACE(REPLACE(stg."ValorLiquidoPedido(R$)",'R$',''),' ',''),'.',''),',','.') AS DECIMAL(15,2))
        ELSE CAST(REPLACE(REPLACE(stg."ValorLiquidoPedido(R$)",'R$',''),' ','') AS DECIMAL(15,2)) 
    END AS vl_liquido,
    
    -- Dias de intervalo
    CASE WHEN NULLIF(TRIM(stg."Dt Separacao Estoque"), '') IS NULL THEN NULL 
         ELSE stg."Dt Separacao Estoque"::date - TO_TIMESTAMP(stg."DtHoraIntegracaoERP", 'MM/DD/YYYY HH12:MI AM')::date END AS dias_integracao_separacao,
         
    CASE WHEN NULLIF(TRIM(stg."DtNotaFiscal"), '') IS NULL THEN NULL 
         ELSE stg."DtNotaFiscal"::date - stg."Dt Separacao Estoque"::date END AS dias_separacao_nota,
         
    CASE WHEN NULLIF(TRIM(stg."Dt_Despacho_Transportadora"), '') IS NULL THEN NULL 
         ELSE stg."Dt_Despacho_Transportadora"::date - stg."DtNotaFiscal"::date END AS dias_nota_despacho,
         
    CASE WHEN NULLIF(TRIM(stg."DtEntregaCliente"), '') IS NULL THEN NULL 
         ELSE stg."DtEntregaCliente"::date - stg."Dt_Despacho_Transportadora"::date END AS dias_despacho_entrega,
         
    CASE WHEN NULLIF(TRIM(stg."DtEntregaCliente"), '') IS NULL THEN NULL 
         ELSE stg."DtEntregaCliente"::date - TO_TIMESTAMP(stg."DtHoraIntegracaoERP", 'MM/DD/YYYY HH12:MI AM')::date END AS dias_total_ate_entrega

FROM stg_pedido stg
LEFT JOIN dim_categoria c ON stg."CategoriaProduto" = c.categoria_origem

LEFT JOIN dim_loja l ON l.chave_loja = 
    CASE 
       -- 1. Primeiro testamos as exceções, mas já garantindo que estão em maiúsculo e sem o /SC
        WHEN UPPER(REPLACE(TRIM(stg."Loja-Nome"), '/SC', '')) = 'PATA AMIGA BLUMENAL CENTRO' THEN 'PATA AMIGA BLUMENAU CENTRO'
        WHEN UPPER(REPLACE(TRIM(stg."Loja-Nome"), '/SC', '')) = 'PATA AMIGA FLORIPA NORTE' THEN 'PATA AMIGA FLORIANOPOLIS NORTE'
        WHEN UPPER(REPLACE(TRIM(stg."Loja-Nome"), '/SC', '')) = 'PATA AMIGA JGUA DO SUL' THEN 'PATA AMIGA JARAGUA DO SUL'
        
        -- 2. Depois aplicamos a regra geral para o resto (sem acentos e espaços duplos)
        ELSE UPPER(TRANSLATE(REPLACE(REPLACE(REPLACE(TRIM(stg."Loja-Nome"), '/SC', ''), '/ SC', ''), '  ', ' '), 'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç', 'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc'))
    END;

-- 3. AUDITORIA FINAL
SELECT 'fato_pedido carregada com sucesso!' AS status, COUNT(*) AS total_linhas FROM fato_pedido;